"""Q12

Revision ID: c42b16a52908
Revises: bf0af614d24e
Create Date: 2025-04-15 02:20:00.123597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c42b16a52908'
down_revision = 'bf0af614d24e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=1),
               existing_nullable=True)

    # ### end Alembic commands ###
